### ISSUE TITLE
Split 'iso codes'

### ISSUE THREAD

**Issue by Meisterschueler** [Collen-Roller/arp#2]
Current state:
{'iso codes': "['US', 'USA']"}
The string "['US', 'USA']" need further steps until we get the iso2 or iso3

Better (in my opinion):
{'iso codes': ['US', 'USA']}
or
{'iso2': 'US', 'iso3': 'USA'}

**Comment by Collen-Roller** [comment]
Good suggestions,

I updated the version (https://pypi.org/project/flydenity/0.1.3/)

Changed requirements suggestion
Also modified string representation of list to an actual list for parsing
convenience.

Hope this helps

Collen
